### ISSUE TITLE
Windows detects Trojan Win32/Zpevdo.A

### ISSUE THREAD

**Issue by RobKra** [ThibautSF/ParadoxosModManagerRework#15]
All Windows Releases get detected as Trojan Win32/Zpevdo.A.

**Comment by ThibautSF** [comment]
It's a problem with the .exe
Sorry for the inconvenience...

This exe is generated by another tool in order to start a bat script file which runs PMM silently. The other way is to use the .bat file in the root folder which do the same thing (but with an annoying black cmd terminal...)

**Comment by RobKra** [comment]
Thanks for the fast response, I expected something like this.
For me a cmd terminal is nothing unusal.^^

From my perspective a disclamer that it probably gets detected as a Trojan would be enouth, or that people who dont want take the risk, can use the bat script instead.

I just searched for it and didn't found an answer.
