### ISSUE TITLE
Mod Conflict marking error

### ISSUE THREAD

**Issue by kesa0v0** [ThibautSF/ParadoxosModManagerRework#25]
![image](https://user-images.githubusercontent.com/43911452/78360264-7f357780-75f1-11ea-9275-83287a72c2fd.png)

When conflict manager is on,
It should be un-marked when it is disabled, but it still marked.

1. Enable mod
2. Disable mod in ordering space in right side.

**Comment by kesa0v0** [comment]
It happened in "Stellaris >= 2.4" and I am running on Windows.

**Comment by ThibautSF** [comment]
Is it still appears in the right column?

**Comment by kesa0v0** [comment]
no. disappeared in the right column but still marked in left column

**Comment by ThibautSF** [comment]
So it might be only a visual bug.
