### ISSUE TITLE
Import from current reverse order

### ISSUE THREAD

**Issue by Niamor** [ThibautSF/ParadoxosModManagerRework#26]
Hello,

When importing from current it imports in the order in the Paradox Launcher is which is if I understand correctly the opposite of what PMM does if custom order is ticked.
Could it be possible to have it reversed or / even better have an option to have the custom order act like the new Paradox Launcher when #1 gets loaded first and not last.
Tested on Stellaris.

Thanks for the great tool.

**Comment by ThibautSF** [comment]
Already fixed in commit 70e10e4ffce3e31f7953f1815e04f3da8a0fc31e
Modification suggested in the Paradox official forum.

Not released but available in the current (and future) [Indev builds](https://github.com/ThibautSF/ParadoxosModManagerRework/releases/tag/indev)

**Comment by Niamor** [comment]
Oh my bad I didn't realize, thanks a lot.
