### ISSUE TITLE
No simp_chinese can be chose for Stellaris

### ISSUE THREAD

**Issue by irosdp** [ThibautSF/ParadoxosModManagerRework#38]
FYI

**Comment by ThibautSF** [comment]
In fact I'm not sure that this function even work now ^^'

It's an old function and simp_chinese wasn't supported at the time. I put that as enhancement.

**Comment by irosdp** [comment]
I found out that will overwrite my language selection. Every time I apply a new mod config, the game language will change into English, but Game Launcher still using Chinese.
In the directory "C:\Users\UserName\Documents\Paradox Interactive\Stellaris"
I found out that "settings.txt" still include "language="l_simp_chinese"
But "pdx_settings.txt" will become below, and I have to change it manually

> "System"={
> 	"language"={
> 		version=0
> 		value="l_english"

Hope this reply will help, thanks for your great work :)

**Comment by ThibautSF** [comment]
Should be available in [Indev](https://github.com/ThibautSF/ParadoxosModManagerRework/releases/tag/indev) release now

**Comment by irosdp** [comment]
I've tried and working just fine, cool
