### ISSUE TITLE
[Major] Import/Export Function not working correctly

### ISSUE THREAD

**Issue by Toriansel** [ThibautSF/ParadoxosModManagerRework#4]
The Import/Export doesn't seem to work as intended. The export exports the current set as an xml file. While the Import allows selecting an xml file but then doesn't import it. And the debug log contains the following.

[DebugLog.txt](https://github.com/ThibautSF/ParadoxosModManagerRework/files/4208995/DebugLog.txt)

**Comment by ThibautSF** [comment]
OK I will look that.

Should be JSON files, but I think I forgot Tu update some part of the code...

**Comment by ThibautSF** [comment]
Should be ready for 0.8.1
