### ISSUE TITLE
Steps to launch mods

### ISSUE THREAD

**Issue by ICodeMaster** [ThibautSF/ParadoxosModManagerRework#46]
Hello, 
I currently work on a mod for HOI4, and we are currently trying to get our docker to run HOI4 + our mod without the launcher. We were wondering how you set the mods to launch outside of the launcher, as getting HOI4 to launch mods via arguments has not been fruitful (despite it seeming to work pre launcher-v2). 

We've found an sql-lite database that controls a mod's status in the launcher, but editing this database only affect the game if the launcher is currently running and the "Mods" button is pressed, then hoi4 is launched via command line. Obviously we would like to launch hoi4 with the mod enabled directly.

Thanks so much for any information you can provide!

**Comment by bcssov** [comment]
dlc_load.json enabled_mods is what you're looking for.

**Comment by ICodeMaster** [comment]
Wow, how did we miss that! Thank you so much!
