### ISSUE TITLE
Export fails on special characters

### ISSUE THREAD

**Issue by Pixelz** [ThibautSF/ParadoxosModManagerRework#6]
Export fails if the list name contains special characters not allowed for filenames in windows. It creates an empty file with the name after the special character cropped.

Steps to reproduce:
- Create a new list with the name "Foo: Bar" and add some mods to it.
- Export it, it will create an empty file called "Export_Game Name_Foo"

**Comment by ThibautSF** [comment]
All special chars are now removed (Hope I didn't forget any...)

Example
List `foo:bar` is exported in `Export_Stellaris_foobar.json`
List `\\\\/:*?\"<>|...*` is exported in `Export_Stellaris_WhyYouUseOnlySpecialChar.json`

Import keep the real name
![image](https://user-images.githubusercontent.com/9386581/74605172-d7f29480-50c5-11ea-85fe-9e523642982c.png)

**Comment by ThibautSF** [comment]
Should be ready for 0.8.1
